# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Set ARG for the jar file
ARG JAR_FILE=target/*.jar

# Copy the jar file into the container
COPY ${JAR_FILE} app.jar

# Copy the application.properties file
COPY src/main/resources/application.properties /application.properties

# Run the jar file and specify the location of the properties file
ENTRYPOINT ["java","-jar","/app.jar","--spring.config.location=file:/application.properties"]
