# Stage 1: Build the JAR
FROM maven:3.8.7-openjdk-17
# Set the working directory in the container
WORKDIR /app

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the source code
COPY . .

# Package the application (build the JAR)
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM openjdk:17-jdk-alpine

# Set the working directory for the application
WORKDIR /app

# Copy the JAR from the previous stage
COPY --from=build /app/target/product-service-0.0.1-SNAPSHOT.jar /app/product-service.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/product-service.jar"]
