version: "3.8"
services:
  postgres-products:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  postgres-orders:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: orders
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  mongo:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - db-network

volumes:
  postgres-data:
  mongo-data:

networks:
  db-network:
