# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
WORKDIR /source

# Copy project file and restore as distinct layers
COPY --link orders-service/*.csproj .
RUN dotnet restore -a $TARGETARCH

# Copy source code and publish app
COPY --link orders-service/. .
RUN dotnet run --background


# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
EXPOSE 3001
WORKDIR /app
COPY --link --from=build /app .
USER $APP_UID
ENTRYPOINT ["./aspnetapp"]