

# Stage 2: Run the application
FROM openjdk:17-jdk-alpine

# Set the working directory for the application
WORKDIR /app

# Copy the JAR from the previous stage
COPY /target/product-service-0.0.1-SNAPSHOT.jar /app/product-service.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/product-service.jar"]
